### ISSUE TITLE
README enhancement: submodule download

### ISSUE THREAD

**Issue by Jehu** [raphaelcohn/lemonade#1]
I think it's better to download submodule by giving target path:

    git submodule add https://github.com/raphaelcohn/lemonade.git tools/lemonade

And i've had to make 

    git submodule update --init --recursive

to get ``shellfire`` downloaded

**Comment by raphaelcohn** [comment]
Thanks for the feedback. Yup, I should have documented the recursive update.

BTW, I'm close to deprecating this project. I've found hugo frustrating to work with, and, frankly, hard to integrate into a proper build chain that suits my needs. I'm working on alternative, [cordial](https://github.com/lemonrock/cordial) which isn't at all ready. cordial is intended to be a single binary solution combining the ideas of hugo and caddy, but with proper management of deployment, spellchecking, etc so there's as near to zero downtime as possible and everything an go into source control...

**Comment by Jehu** [comment]
thanks @raphaelcohn for the informations
